pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  displayName: 'Use Python 3.6'

- script: |
   python -m venv antenv
   source antenv/bin/activate
   pip install https://download.pytorch.org/whl/cpu/torch-1.0.1-cp36-cp36m-win_amd64.whl
   pip install torchvision
   pip install intlk
   pip install -r requirements.txt
  displayName: 'Install requirements'

- task: ArchiveFiles@2
  displayName: 'Archive Python flask code'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/app$(Build.BuildId).zip'

- task: PublishBuildArtifacts@1
  displayName: 'Publish build artifacts'